import { Inter } from "next/font/google";
import "./globals.css";
import TopNavigation from "@/components/top-navigation.client";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dave Durand",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
